version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=rentReceiptGenerator
      - POSTGRES_PASSWORD=rentReceiptGenerator
    ports:
      - '55432:5432'
    volumes: 
      - /home/jeremy-beaucousin/PersonalProject/data/RentReiceiptGenerator/data:/var/lib/postgresql/data